# Generated by Django 5.0 on 2023-12-14 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moon', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Header',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
